spring.application.name=todo

de.flapdoodle.mongodb.embedded.version=7.0.12

spring.mongodb.uri=mongodb+srv://mohanthi:born2win@readit-cluster.in5aqgt.mongodb.net/todo?retryWrites=true&w=majority&appName=readit-cluster
